services:


  php:
    build: . 

    ports:
      - "8080:80" 

    volumes:
      - .:/var/www/html 

    environment:

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ENV: ${APP_ENV}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
      ORS_API_KEY: ${ORS_API_KEY}
      ORS_BORDEAUX_LAT: ${ORS_BORDEAUX_LAT}
      ORS_BORDEAUX_LNG: ${ORS_BORDEAUX_LNG}
      MAILTRAP_HOST: ${MAILTRAP_HOST}
      MAILTRAP_PORT: ${MAILTRAP_PORT}
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
      APP_URL: ${APP_URL}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}

    depends_on:
      - mysql 
      - mongodb
  
  mongodb:
    image: mongo:7
    container_name: vite_gourmand_mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db


  mysql:
    image: mysql:8.0 

    environment:
      
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME} 

    ports:
      - "3310:3306" 

    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data:
  mongodb_data: